name: Build All ISOs
on:
  schedule:
    - cron: "50 4 * * 0" # 4:50 UTC Sunday
  workflow_dispatch:

permissions:
    contents: read
    packages: write
    id-token: write

jobs:
    build-iso-latest:
        uses: ./.github/workflows/build-iso-latest.yml
        secrets: inherit
