name: Stable Images
on:
  merge_group:
  workflow_call:
  workflow_dispatch:

jobs:
  build-image-stable:
    name: Build Stable Images
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        brand_name: ["silverblue"]
    with:
      image_flavors: '["main", "nvidia-open"]'
      brand_name: ${{ matrix.brand_name }}
      stream_name: stable

  # generate-release:
  #   name: Generate Release
  #   needs: [build-image-latest]
  #   secrets: inherit
  #   uses: ./.github/workflows/generate-release.yml
  #   with:
  #     stream_name: '["latest"]'

  # build-iso-latest:
  #   name: Build Latest ISOs
  #   needs: [build-image-latest]
  #   if: github.event.schedule == '50 4 * * 0'
  #   secrets: inherit
  #   uses: ./.github/workflows/build-iso-latest.yml
